#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/prepare-private-fragment.sh <profile-json> <workspace-dir>

Generates common/private.fragment, common/private.required,
common/lto.fragment, common/features.fragment, and
common/coreshift.kleaf.fragment from the CoreShift default fragment plus
an optional repo-root private.fragment.
EOF
}

if [ "$#" -ne 2 ]; then
  usage >&2
  exit 1
fi

command -v python3 >/dev/null 2>&1 || {
  echo "Missing required tool: python3" >&2
  exit 1
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PROFILE_JSON="$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
WORKSPACE_DIR="$2"
COMMON_DIR="$WORKSPACE_DIR/common"
DEFAULT_FRAGMENT="$REPO_ROOT/configs/fragments/coreshift.fragment"
USER_FRAGMENT="$REPO_ROOT/private.fragment"
GENERATED_FRAGMENT="$COMMON_DIR/private.fragment"
REQUIRED_FRAGMENT="$COMMON_DIR/private.required"
LTO_FRAGMENT="$COMMON_DIR/lto.fragment"
FEATURES_FRAGMENT="$COMMON_DIR/features.fragment"
KLEAF_FRAGMENT="$COMMON_DIR/coreshift.kleaf.fragment"
BUILD_BAZEL="$COMMON_DIR/BUILD.bazel"
GKI_DEFCONFIG="$COMMON_DIR/arch/arm64/configs/gki_defconfig"
MERGE_CONFIG_SH="$COMMON_DIR/scripts/kconfig/merge_config.sh"
WRAPPER_BUILD_CONFIG="$COMMON_DIR/build.config.coreshift.gki.aarch64"

if [ ! -f "$PROFILE_JSON" ]; then
  echo "Profile not found: $PROFILE_JSON" >&2
  exit 1
fi

if [ ! -d "$COMMON_DIR" ]; then
  echo "Workspace common directory not found: $COMMON_DIR" >&2
  exit 1
fi

if [ ! -f "$DEFAULT_FRAGMENT" ]; then
  echo "CoreShift default fragment not found: $DEFAULT_FRAGMENT" >&2
  exit 1
fi

eval "$(
  python3 - "$PROFILE_JSON" <<'PY'
import json
import shlex
import sys

profile_path = sys.argv[1]

with open(profile_path, encoding="utf-8") as fh:
    profile = json.load(fh)

for field in ("build_config", "bazel_target"):
    value = profile.get(field)
    if value is None:
        print(f"{field.upper()}=''")
    elif isinstance(value, str) and value:
        print(f"{field.upper()}={shlex.quote(value)}")
    else:
        raise SystemExit(
            f"{profile_path}: profile field {field!r} must be a non-empty string or null"
        )

name = profile.get("name")
if not isinstance(name, str) or not name:
    raise SystemExit(f"{profile_path}: profile field 'name' must be a non-empty string")
print(f"PROFILE_NAME={shlex.quote(name)}")

lto = profile.get("lto", "full")
if lto not in {"full", "thin", "none", "default"}:
    raise SystemExit(
        f"{profile_path}: profile field 'lto' must be one of: full, thin, none, default"
    )
print(f"PROFILE_LTO={shlex.quote(lto)}")
PY
)"

if [ ! -f "$GKI_DEFCONFIG" ]; then
  echo "Missing base ACK defconfig: $GKI_DEFCONFIG" >&2
  exit 1
fi

GKI_DEFCONFIG_SHA_BEFORE="$(sha256sum "$GKI_DEFCONFIG" | awk '{print $1}')"

python3 - "$DEFAULT_FRAGMENT" "$USER_FRAGMENT" "$GENERATED_FRAGMENT" "$REQUIRED_FRAGMENT" "$LTO_FRAGMENT" "$FEATURES_FRAGMENT" "$KLEAF_FRAGMENT" "$PROFILE_NAME" "$PROFILE_LTO" <<'PY'
from pathlib import Path
import sys

default_fragment = Path(sys.argv[1])
user_fragment = Path(sys.argv[2])
generated_fragment = Path(sys.argv[3])
required_fragment = Path(sys.argv[4])
lto_fragment = Path(sys.argv[5])
features_fragment = Path(sys.argv[6])
kleaf_fragment = Path(sys.argv[7])
profile_name = sys.argv[8]
profile_lto = sys.argv[9]

def read_normalized(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8").replace("\r\n", "\n").replace("\r", "\n")

def with_trailing_newline(text: str) -> str:
    if not text:
        return ""
    return text if text.endswith("\n") else text + "\n"

parts = [
    "# Generated by scripts/prepare-private-fragment.sh\n"
    "# Layer order: base ACK defconfig, CoreShift default fragment, user private.fragment last\n"
    "\n"
]

default_text = read_normalized(default_fragment)
user_text = read_normalized(user_fragment)

if profile_name == "android16-6.12-lts":
    profile_lto = "thin"
    forbidden_lines = {
        "CONFIG_LTO_NONE=y": (
            "android16-6.12-lts forces ThinLTO and does not allow "
            "CONFIG_LTO_NONE=y in private.fragment."
        ),
        "CONFIG_LTO_CLANG_FULL=y": (
            "android16-6.12-lts does not allow CONFIG_LTO_CLANG_FULL=y in "
            "private.fragment because full LTO breaks rust_binder.ko output."
        ),
        "# CONFIG_LTO_CLANG_THIN is not set": (
            "android16-6.12-lts forces ThinLTO and does not allow "
            "# CONFIG_LTO_CLANG_THIN is not set in private.fragment."
        ),
    }
    for line in user_text.splitlines():
        stripped = line.strip()
        if stripped in forbidden_lines:
            raise SystemExit(forbidden_lines[stripped])

if default_text:
    parts.append(default_text if default_text.endswith("\n") else default_text + "\n")

if user_text:
    parts.append(user_text if user_text.endswith("\n") else user_text + "\n")

final_text = "".join(parts)
lto_texts = {
    "full": (
        "# CoreShift generated LTO policy: full\n"
        "# CONFIG_LTO_NONE is not set\n"
        "CONFIG_LTO_CLANG=y\n"
        "# CONFIG_LTO_CLANG_THIN is not set\n"
        "CONFIG_LTO_CLANG_FULL=y\n"
    ),
    "thin": (
        "# CoreShift generated LTO policy: thin\n"
        "# CONFIG_LTO_NONE is not set\n"
        "CONFIG_LTO_CLANG=y\n"
        "CONFIG_LTO_CLANG_THIN=y\n"
        "# CONFIG_LTO_CLANG_FULL is not set\n"
    ),
    "none": (
        "# CoreShift generated LTO policy: none\n"
        "CONFIG_LTO_NONE=y\n"
        "# CONFIG_LTO_CLANG_THIN is not set\n"
        "# CONFIG_LTO_CLANG_FULL is not set\n"
    ),
    "default": (
        "# CoreShift generated LTO policy: default\n"
        "# No LTO override for this profile.\n"
    ),
}
lto_text = lto_texts[profile_lto]
features_text = (
    "# Generated by scripts/prepare-private-fragment.sh\n"
    "# Variant-owned fragment. Feature scripts may rewrite this file.\n"
    "\n"
)
kleaf_text = (
    with_trailing_newline(final_text)
    + with_trailing_newline(lto_text)
    + with_trailing_newline(features_text)
)

generated_fragment.write_text(final_text, encoding="utf-8")
required_fragment.write_text(final_text, encoding="utf-8")
lto_fragment.write_text(with_trailing_newline(lto_text), encoding="utf-8")
features_fragment.write_text(features_text, encoding="utf-8")
kleaf_fragment.write_text(kleaf_text, encoding="utf-8")
PY

if [ ! -f "$USER_FRAGMENT" ]; then
  echo "No user private.fragment found. To customize, copy configs/fragments/private.fragment.example to private.fragment."
fi

echo "Generated fragment: $GENERATED_FRAGMENT"
cat "$GENERATED_FRAGMENT"
echo "Generated LTO fragment: $LTO_FRAGMENT"
cat "$LTO_FRAGMENT"
echo "Generated features fragment: $FEATURES_FRAGMENT"
cat "$FEATURES_FRAGMENT"

if [ -n "$BAZEL_TARGET" ]; then
  if [ ! -f "$BUILD_BAZEL" ]; then
    echo "Missing BUILD.bazel for Bazel profile: $BUILD_BAZEL" >&2
    exit 1
  fi

  python3 - "$BUILD_BAZEL" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")
missing = []
for filename in ("private.fragment", "lto.fragment", "features.fragment", "coreshift.kleaf.fragment"):
    if f'"{filename}"' in text or f"'{filename}'" in text:
        continue
    missing.append(filename)

if not missing:
    print(f"BUILD.bazel already exports CoreShift fragments: {path}")
    raise SystemExit(0)

if text and not text.endswith("\n"):
    text += "\n"

quoted = ", ".join(f'"{name}"' for name in missing)
text += f'\nexports_files([{quoted}])\n'
path.write_text(text, encoding="utf-8")
print(f"Added CoreShift fragment exports to {path}: {', '.join(missing)}")
PY
fi

if [ -n "$BUILD_CONFIG" ]; then
  if [ ! -f "$WORKSPACE_DIR/$BUILD_CONFIG" ]; then
    echo "Profile build_config not found in workspace: $WORKSPACE_DIR/$BUILD_CONFIG" >&2
    exit 1
  fi

  if [ ! -f "$MERGE_CONFIG_SH" ]; then
    echo "Missing merge_config helper: $MERGE_CONFIG_SH" >&2
    exit 1
  fi

  cat > "$WRAPPER_BUILD_CONFIG" <<EOF
# Generated by scripts/prepare-private-fragment.sh
. "\${ROOT_DIR:-\$(pwd)}/${BUILD_CONFIG}"

CORESHIFT_BASE_DEFCONFIG="\${DEFCONFIG:-gki_defconfig}"
CORESHIFT_DEFCONFIG="coreshift_\${CORESHIFT_BASE_DEFCONFIG}"
CORESHIFT_CONFIG_DIR="\${ROOT_DIR:-\$(pwd)}/common/arch/arm64/configs"
CORESHIFT_MERGE_CONFIG="\${ROOT_DIR:-\$(pwd)}/common/scripts/kconfig/merge_config.sh"
CORESHIFT_PRIVATE_FRAGMENT="\${ROOT_DIR:-\$(pwd)}/common/private.fragment"
CORESHIFT_LTO_FRAGMENT="\${ROOT_DIR:-\$(pwd)}/common/lto.fragment"
CORESHIFT_FEATURES_FRAGMENT="\${ROOT_DIR:-\$(pwd)}/common/features.fragment"
CORESHIFT_TEMP_DEFCONFIG="\${CORESHIFT_CONFIG_DIR}/\${CORESHIFT_DEFCONFIG}"
CORESHIFT_BASE_DEFCONFIG_PATH="\${CORESHIFT_CONFIG_DIR}/\${CORESHIFT_BASE_DEFCONFIG}"

CORESHIFT_PRE_DEFCONFIG_CMDS="KCONFIG_CONFIG=\${CORESHIFT_TEMP_DEFCONFIG} \${CORESHIFT_MERGE_CONFIG} -m -r \${CORESHIFT_BASE_DEFCONFIG_PATH} \${CORESHIFT_PRIVATE_FRAGMENT} \${CORESHIFT_LTO_FRAGMENT} \${CORESHIFT_FEATURES_FRAGMENT}"
if [ -n "\${PRE_DEFCONFIG_CMDS:-}" ]; then
  PRE_DEFCONFIG_CMDS="\${PRE_DEFCONFIG_CMDS} && \${CORESHIFT_PRE_DEFCONFIG_CMDS}"
else
  PRE_DEFCONFIG_CMDS="\${CORESHIFT_PRE_DEFCONFIG_CMDS}"
fi

CORESHIFT_POST_DEFCONFIG_CMDS="rm -f \${CORESHIFT_TEMP_DEFCONFIG}"
if [ -n "\${POST_DEFCONFIG_CMDS:-}" ]; then
  POST_DEFCONFIG_CMDS="\${POST_DEFCONFIG_CMDS} && \${CORESHIFT_POST_DEFCONFIG_CMDS}"
else
  POST_DEFCONFIG_CMDS="\${CORESHIFT_POST_DEFCONFIG_CMDS}"
fi

DEFCONFIG="\${CORESHIFT_DEFCONFIG}"
EOF

  GKI_DEFCONFIG_SHA_AFTER="$(sha256sum "$GKI_DEFCONFIG" | awk '{print $1}')"
  if [ "$GKI_DEFCONFIG_SHA_BEFORE" != "$GKI_DEFCONFIG_SHA_AFTER" ]; then
    echo "Base ACK defconfig changed while preparing wrapper: $GKI_DEFCONFIG" >&2
    exit 1
  fi

  echo "Generated wrapper build config: $WRAPPER_BUILD_CONFIG"
  cat "$WRAPPER_BUILD_CONFIG"
fi
